// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlximnzppcikepzzkfmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhseGltbnpwcGNpa2VwenprZm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMTA1ODcsImV4cCI6MjA1MTY4NjU4N30.Lcib5UX-YGq1oaorQNwOGvuBYGsbUjdNljzG4vz7moI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);